#!/usr/bin/env python3

class InstructionClass:
    def __init__(self,k,v):
        self.key=k
        self.mask_raw=v[0]
        self.group=v[1]
        self.mask=0
        self.id=0
        self.operand_masks={}

        #Generate mask and id
        for c in self.mask_raw:
            self.mask<<=1
            self.id<<=1
            if c=="1":
                self.mask|=1
                self.id|=1
            elif c=="0":
                self.mask|=1

        #Generate field masks
        fields=extract_fields(self.mask_raw)

        for field in fields:
            letter,start,length=field
            mask=((1<<length)-1)<<start
            self.operand_masks[letter]=(start,length,mask)


instructions={}
opcode_lookup={}
token_lookup={}

#Extract fields from mask
    #Needed to load instructions so not part of LineClass
def extract_fields(mask):
    fields=[]
    char=None
    start=None
    length=0
    for i,c in enumerate(mask[::-1]):
        if c!=char:
            #Different character found or at end of mask
            if start!=None:
                #Accumulating mask - add to results
                fields+=[(char,start,length)]
                start=None
        else:
            #Character is same as last character
            if start!=None:
                #Character is part of field
                length+=1

        if start==None:
            #Ready to start new field
            if c in "dimn":
                #Start new field
                char=c
                start=i
                length=1

    if start!=None:
        #Field data left over at end to add
        fields+=[(char,start,length)]

    return fields             

#AUTO-GENERATED BY SPREADSHEET!
    #Do not modify here
modes={
"REG_R0":("R0","R0"),
"REG_GBR":("GBR","GBR"),
"REG_PR":("PR","PR"),
"REG_DIR":("Rm","Rn"),
"REG_MACH":("MACH","MACH"),
"REG_MACL":("MACL","MACL"),
"REG_IND":("@Rm","@Rn"),
"REG_IND_POST":("@Rm+","@Rn+"),
"REG_IND_PRE":("@-Rm","@-Rn"),
"REG_IND_DISP":("@(disp,Rm)","@(disp,Rn)"),
"IND_REG_IND":("@(R0,Rm)","@(R0,Rn)"),
"GBR_IND_DISP":("@(disp,GBR)","@(disp,GBR)"),
"IND_GBR_IND":("@(R0,GBR)","@(R0,GBR)"),
"PC_REL_DISP":("@(disp,PC)","@(disp,PC)"),
"PC_REL_8":("disp","disp"),
"PC_REL_12":("disp","disp"),
"IMM8_UNSIGNED":("#imm","#imm"),
"IMM8_SIGNED":("#imm","#imm"),
"REG_SR":("SR","SR"),
"REG_VBR":("VBR","VBR"),
"REG_SSR":("SSR","SSR"),
"REG_SPC":("SPC","SPC"),
"REG_SGR":("SGR","SGR"),
"REG_DBR":("DBR","DBR"),
"REG_BANK":("Rm_BANK","Rn_BANK"),
"FREG_DIR":("FRm","FRn"),
"DREG_DIR":("DRm","DRn"),
"REG_FPUL":("FPUL","FPUL"),
"FREG_FR0_DIR":("FR0,FRm","FR0,FRn"),
"REG_FPSCR":("FPSCR","FPSCR"),
"XREG_DIR":("XDm","XDn"),
"FVREG_DIR":("FVm","FVn"),
"REG_XMTRX":("XMTRX","XMTRX"),
"PC_REL_ABS":("abs","abs"),
}

instructions_raw={
("MOV","IMM8_SIGNED","REG_DIR"):("1110nnnniiiiiiii","EX"),
("MOV.W","PC_REL_ABS","REG_DIR"):("1001nnnndddddddd","LS"),
("MOV.L","PC_REL_ABS","REG_DIR"):("1101nnnndddddddd","LS"),
("MOV.W","PC_REL_DISP","REG_DIR"):("1001nnnndddddddd","LS"),
("MOV.L","PC_REL_DISP","REG_DIR"):("1101nnnndddddddd","LS"),
("MOV","REG_DIR","REG_DIR"):("0110nnnnmmmm0011","MT"),
("MOV.B","REG_DIR","REG_IND"):("0010nnnnmmmm0000","LS"),
("MOV.W","REG_DIR","REG_IND"):("0010nnnnmmmm0001","LS"),
("MOV.L","REG_DIR","REG_IND"):("0010nnnnmmmm0010","LS"),
("MOV.B","REG_IND","REG_DIR"):("0110nnnnmmmm0000","LS"),
("MOV.W","REG_IND","REG_DIR"):("0110nnnnmmmm0001","LS"),
("MOV.L","REG_IND","REG_DIR"):("0110nnnnmmmm0010","LS"),
("MOV.B","REG_DIR","REG_IND_PRE"):("0010nnnnmmmm0100","LS"),
("MOV.W","REG_DIR","REG_IND_PRE"):("0010nnnnmmmm0101","LS"),
("MOV.L","REG_DIR","REG_IND_PRE"):("0010nnnnmmmm0110","LS"),
("MOV.B","REG_IND_POST","REG_DIR"):("0110nnnnmmmm0100","LS"),
("MOV.W","REG_IND_POST","REG_DIR"):("0110nnnnmmmm0101","LS"),
("MOV.L","REG_IND_POST","REG_DIR"):("0110nnnnmmmm0110","LS"),
("MOV.B","REG_R0","REG_IND_DISP"):("10000000nnnndddd","LS"),
("MOV.W","REG_R0","REG_IND_DISP"):("10000001nnnndddd","LS"),
("MOV.L","REG_DIR","REG_IND_DISP"):("0001nnnnmmmmdddd","LS"),
("MOV.B","REG_IND_DISP","REG_R0"):("10000100mmmmdddd","LS"),
("MOV.W","REG_IND_DISP","REG_R0"):("10000101mmmmdddd","LS"),
("MOV.L","REG_IND_DISP","REG_DIR"):("0101nnnnmmmmdddd","LS"),
("MOV.B","REG_DIR","IND_REG_IND"):("0000nnnnmmmm0100","LS"),
("MOV.W","REG_DIR","IND_REG_IND"):("0000nnnnmmmm0101","LS"),
("MOV.L","REG_DIR","IND_REG_IND"):("0000nnnnmmmm0110","LS"),
("MOV.B","IND_REG_IND","REG_DIR"):("0000nnnnmmmm1100","LS"),
("MOV.W","IND_REG_IND","REG_DIR"):("0000nnnnmmmm1101","LS"),
("MOV.L","IND_REG_IND","REG_DIR"):("0000nnnnmmmm1110","LS"),
("MOV.B","REG_R0","GBR_IND_DISP"):("11000000dddddddd","LS"),
("MOV.W","REG_R0","GBR_IND_DISP"):("11000001dddddddd","LS"),
("MOV.L","REG_R0","GBR_IND_DISP"):("11000010dddddddd","LS"),
("MOV.B","GBR_IND_DISP","REG_R0"):("11000100dddddddd","LS"),
("MOV.W","GBR_IND_DISP","REG_R0"):("11000101dddddddd","LS"),
("MOV.L","GBR_IND_DISP","REG_R0"):("11000110dddddddd","LS"),
("MOVA","PC_REL_ABS","REG_R0"):("11000111dddddddd","EX"),
("MOVA","PC_REL_DISP","REG_R0"):("11000111dddddddd","EX"),
("MOVT","","REG_DIR"):("0000nnnn00101001","EX"),
("SWAP.B","REG_DIR","REG_DIR"):("0110nnnnmmmm1000","EX"),
("SWAP.W","REG_DIR","REG_DIR"):("0110nnnnmmmm1001","EX"),
("XTRCT","REG_DIR","REG_DIR"):("0010nnnnmmmm1101","EX"),
("ADD","REG_DIR","REG_DIR"):("0011nnnnmmmm1100","EX"),
("ADD","IMM8_SIGNED","REG_DIR"):("0111nnnniiiiiiii","EX"),
("ADDC","REG_DIR","REG_DIR"):("0011nnnnmmmm1110","EX"),
("ADDV","REG_DIR","REG_DIR"):("0011nnnnmmmm1111","EX"),
("CMP/EQ","IMM8_SIGNED","REG_R0"):("10001000iiiiiiii","MT"),
("CMP/EQ","REG_DIR","REG_DIR"):("0011nnnnmmmm0000","MT"),
("CMP/HS","REG_DIR","REG_DIR"):("0011nnnnmmmm0010","MT"),
("CMP/GE","REG_DIR","REG_DIR"):("0011nnnnmmmm0011","MT"),
("CMP/HI","REG_DIR","REG_DIR"):("0011nnnnmmmm0110","MT"),
("CMP/GT","REG_DIR","REG_DIR"):("0011nnnnmmmm0111","MT"),
("CMP/PZ","","REG_DIR"):("0100nnnn00010001","MT"),
("CMP/PL","","REG_DIR"):("0100nnnn00010101","MT"),
("CMP/STR","REG_DIR","REG_DIR"):("0010nnnnmmmm1100","MT"),
("DIV1","REG_DIR","REG_DIR"):("0011nnnnmmmm0100","EX"),
("DIV0S","REG_DIR","REG_DIR"):("0010nnnnmmmm0111","EX"),
("DIV0U","",""):("0000000000011001","EX"),
("DMULS.L","REG_DIR","REG_DIR"):("0011nnnnmmmm1101","CO"),
("DMULU.L","REG_DIR","REG_DIR"):("0011nnnnmmmm0101","CO"),
("DT","","REG_DIR"):("0100nnnn00010000","EX"),
("EXTS.B","REG_DIR","REG_DIR"):("0110nnnnmmmm1110","EX"),
("EXTS.W","REG_DIR","REG_DIR"):("0110nnnnmmmm1111","EX"),
("EXTU.B","REG_DIR","REG_DIR"):("0110nnnnmmmm1100","EX"),
("EXTU.W","REG_DIR","REG_DIR"):("0110nnnnmmmm1101","EX"),
("MAC.L","REG_IND_POST","REG_IND_POST"):("0000nnnnmmmm1111","CO"),
("MAC.W","REG_IND_POST","REG_IND_POST"):("0100nnnnmmmm1111","CO"),
("MUL.L","REG_DIR","REG_DIR"):("0000nnnnmmmm0111","CO"),
("MULS.W","REG_DIR","REG_DIR"):("0010nnnnmmmm1111","CO"),
("MULU.W","REG_DIR","REG_DIR"):("0010nnnnmmmm1110","CO"),
("NEG","REG_DIR","REG_DIR"):("0110nnnnmmmm1011","EX"),
("NEGC","REG_DIR","REG_DIR"):("0110nnnnmmmm1010","EX"),
("SUB","REG_DIR","REG_DIR"):("0011nnnnmmmm1000","EX"),
("SUBC","REG_DIR","REG_DIR"):("0011nnnnmmmm1010","EX"),
("SUBV","REG_DIR","REG_DIR"):("0011nnnnmmmm1011","EX"),
("AND","REG_DIR","REG_DIR"):("0010nnnnmmmm1001","EX"),
("AND","IMM8_UNSIGNED","REG_R0"):("11001001iiiiiiii","EX"),
("AND.B","IMM8_UNSIGNED","IND_GBR_IND"):("11001101iiiiiiii","CO"),
("NOT","REG_DIR","REG_DIR"):("0110nnnnmmmm0111","EX"),
("OR","REG_DIR","REG_DIR"):("0010nnnnmmmm1011","EX"),
("OR","IMM8_UNSIGNED","REG_R0"):("11001011iiiiiiii","EX"),
("OR.B","IMM8_UNSIGNED","IND_GBR_IND"):("11001111iiiiiiii","CO"),
("TAS.B","","REG_IND"):("0100nnnn00011011","CO"),
("TST","REG_DIR","REG_DIR"):("0010nnnnmmmm1000","MT"),
("TST","IMM8_UNSIGNED","REG_R0"):("11001000iiiiiiii","MT"),
("TST.B","IMM8_UNSIGNED","IND_GBR_IND"):("11001100iiiiiiii","CO"),
("XOR","REG_DIR","REG_DIR"):("0010nnnnmmmm1010","EX"),
("XOR","IMM8_UNSIGNED","REG_R0"):("11001010iiiiiiii","EX"),
("XOR.B","IMM8_UNSIGNED","IND_GBR_IND"):("11001110iiiiiiii","CO"),
("ROTL","","REG_DIR"):("0100nnnn00000100","EX"),
("ROTR","","REG_DIR"):("0100nnnn00000101","EX"),
("ROTCL","","REG_DIR"):("0100nnnn00100100","EX"),
("ROTCR","","REG_DIR"):("0100nnnn00100101","EX"),
("SHAD","REG_DIR","REG_DIR"):("0100nnnnmmmm1100","EX"),
("SHAL","","REG_DIR"):("0100nnnn00100000","EX"),
("SHAR","","REG_DIR"):("0100nnnn00100001","EX"),
("SHLD","REG_DIR","REG_DIR"):("0100nnnnmmmm1101","EX"),
("SHLL","","REG_DIR"):("0100nnnn00000000","EX"),
("SHLR","","REG_DIR"):("0100nnnn00000001","EX"),
("SHLL2","","REG_DIR"):("0100nnnn00001000","EX"),
("SHLR2","","REG_DIR"):("0100nnnn00001001","EX"),
("SHLL8","","REG_DIR"):("0100nnnn00011000","EX"),
("SHLR8","","REG_DIR"):("0100nnnn00011001","EX"),
("SHLL16","","REG_DIR"):("0100nnnn00101000","EX"),
("SHLR16","","REG_DIR"):("0100nnnn00101001","EX"),
("BF","","PC_REL_8"):("10001011dddddddd","BR"),
("BF.S","","PC_REL_8"):("10001111dddddddd","BR"),
("BF/S","","PC_REL_8"):("10001111dddddddd","BR"),
("BT","","PC_REL_8"):("10001001dddddddd","BR"),
("BT.S","","PC_REL_8"):("10001101dddddddd","BR"),
("BT/S","","PC_REL_8"):("10001101dddddddd","BR"),
("BRA","","PC_REL_12"):("1010dddddddddddd","BR"),
("BRAF","","REG_DIR"):("0000nnnn00100011","CO"),
("BSR","","PC_REL_12"):("1011dddddddddddd","BR"),
("BSRF","","REG_DIR"):("0000nnnn00000011","CO"),
("JMP","","REG_IND"):("0100nnnn00101011","CO"),
("JSR","","REG_IND"):("0100nnnn00001011","CO"),
("RTS","",""):("0000000000001011","CO"),
("CLRMAC","",""):("0000000000101000","CO"),
("CLRS","",""):("0000000001001000","CO"),
("CLRT","",""):("0000000000001000","MT"),
("LDC","REG_DIR","REG_GBR"):("0100mmmm00011110","CO"),
("LDC.L","REG_IND_POST","REG_GBR"):("0100mmmm00010111","CO"),
("LDS","REG_DIR","REG_MACH"):("0100mmmm00001010","CO"),
("LDS","REG_DIR","REG_MACL"):("0100mmmm00011010","CO"),
("LDS","REG_DIR","REG_PR"):("0100mmmm00101010","CO"),
("LDS.L","REG_IND_POST","REG_MACH"):("0100mmmm00000110","CO"),
("LDS.L","REG_IND_POST","REG_MACL"):("0100mmmm00010110","CO"),
("LDS.L","REG_IND_POST","REG_PR"):("0100mmmm00100110","CO"),
("MOVCA.L","REG_R0","REG_IND"):("0000nnnn11000011","LS"),
("NOP","",""):("0000000000001001","MT"),
("OCBI","","REG_IND"):("0000nnnn10010011","LS"),
("OCBP","","REG_IND"):("0000nnnn10100011","LS"),
("OCBWB","","REG_IND"):("0000nnnn10110011","LS"),
("PREF","","REG_IND"):("0000nnnn10000011","LS"),
("SETS","",""):("0000000001011000","CO"),
("SETT","",""):("0000000000011000","MT"),
("STC","REG_GBR","REG_DIR"):("0000nnnn00010010","CO"),
("STC.L","REG_GBR","REG_IND_PRE"):("0100nnnn00010011","CO"),
("STS","REG_MACH","REG_DIR"):("0000nnnn00001010","CO"),
("STS","REG_MACL","REG_DIR"):("0000nnnn00011010","CO"),
("STS","REG_PR","REG_DIR"):("0000nnnn00101010","CO"),
("STS.L","REG_MACH","REG_IND_PRE"):("0100nnnn00000010","CO"),
("STS.L","REG_MACL","REG_IND_PRE"):("0100nnnn00010010","CO"),
("STS.L","REG_PR","REG_IND_PRE"):("0100nnnn00100010","CO"),
("STC","REG_SR","REG_DIR"):("0000nnnn00000010","CO"),
("STC","REG_VBR","REG_DIR"):("0000nnnn00100010","CO"),
("STC","REG_SSR","REG_DIR"):("0000nnnn00110010","CO"),
("STC","REG_SPC","REG_DIR"):("0000nnnn01000010","CO"),
("STC","REG_SGR","REG_DIR"):("0000nnnn00111010","CO"),
("STC","REG_DBR","REG_DIR"):("0000nnnn11111010","CO"),
("STC","REG_BANK","REG_DIR"):("0000nnnn1mmm0010","CO"),
("STC.L","REG_SR","REG_IND_PRE"):("0100nnnn00000011","CO"),
("STC.L","REG_VBR","REG_IND_PRE"):("0100nnnn00100011","CO"),
("STC.L","REG_SSR","REG_IND_PRE"):("0100nnnn00110011","CO"),
("STC.L","REG_SPC","REG_IND_PRE"):("0100nnnn01000011","CO"),
("STC.L","REG_SGR","REG_IND_PRE"):("0100nnnn00110010","CO"),
("STC.L","REG_DBR","REG_IND_PRE"):("0100nnnn11110010","CO"),
("STC.L","REG_BANK","REG_IND_PRE"):("0100nnnn1mmm0011","CO"),
("TRAPA","IMM8_UNSIGNED",""):("11000011iiiiiiii","CO"),
("FLDI0","","FREG_DIR"):("1111nnnn10001101","LS"),
("FLDI1","","FREG_DIR"):("1111nnnn10011101","LS"),
("FMOV","FREG_DIR","FREG_DIR"):("1111nnnnmmmm1100","LS"),
("FMOV","REG_IND","FREG_DIR"):("1111nnnnmmmm1000","LS"),
("FMOV","IND_REG_IND","FREG_DIR"):("1111nnnnmmmm0110","LS"),
("FMOV","REG_IND_POST","FREG_DIR"):("1111nnnnmmmm1001","LS"),
("FMOV","FREG_DIR","REG_IND"):("1111nnnnmmmm1010","LS"),
("FMOV","FREG_DIR","REG_IND_PRE"):("1111nnnnmmmm1011","LS"),
("FMOV","FREG_DIR","IND_REG_IND"):("1111nnnnmmmm0111","LS"),
("FMOV","DREG_DIR","DREG_DIR"):("1111nnn0mmm01100","LS"),
("FMOV","REG_IND","DREG_DIR"):("1111nnn0mmmm1000","LS"),
("FMOV","IND_REG_IND","DREG_DIR"):("1111nnn0mmmm0110","LS"),
("FMOV","REG_IND_POST","DREG_DIR"):("1111nnn0mmmm1001","LS"),
("FMOV","DREG_DIR","REG_IND"):("1111nnnnmmm01010","LS"),
("FMOV","DREG_DIR","REG_IND_PRE"):("1111nnnnmmm01011","LS"),
("FMOV","DREG_DIR","IND_REG_IND"):("1111nnnnmmm00111","LS"),
("FLDS","FREG_DIR","REG_FPUL"):("1111mmmm00011101","LS"),
("FSTS","REG_FPUL","FREG_DIR"):("1111nnnn00001101","LS"),
("FABS","","FREG_DIR"):("1111nnnn01011101","LS"),
("FADD","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0000","FE"),
("FCMP/EQ","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0100","FE"),
("FCMP/GT","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0101","FE"),
("FDIV","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0011","FE"),
("FLOAT","REG_FPUL","FREG_DIR"):("1111nnnn00101101","FE"),
("FMAC","FREG_FR0_DIR","FREG_DIR"):("1111nnnnmmmm1110","FE"),
("FMUL","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0010","FE"),
("FNEG","","FREG_DIR"):("1111nnnn01001101","LS"),
("FSQRT","","FREG_DIR"):("1111nnnn01101101","FE"),
("FSUB","FREG_DIR","FREG_DIR"):("1111nnnnmmmm0001","FE"),
("FTRC","FREG_DIR","REG_FPUL"):("1111mmmm00111101","FE"),
("FABS","","DREG_DIR"):("1111nnn001011101","LS"),
("FADD","DREG_DIR","DREG_DIR"):("1111nnn0mmm00000","FE"),
("FCMP/EQ","DREG_DIR","DREG_DIR"):("1111nnn0mmm00100","CO"),
("FCMP/GT","DREG_DIR","DREG_DIR"):("1111nnn0mmm00101","CO"),
("FDIV","DREG_DIR","DREG_DIR"):("1111nnn0mmm00011","FE"),
("FCNVDS","DREG_DIR","REG_FPUL"):("1111mmm010111101","FE"),
("FCNVSD","REG_FPUL","DREG_DIR"):("1111nnn010101101","FE"),
("FLOAT","REG_FPUL","DREG_DIR"):("1111nnn000101101","FE"),
("FMUL","DREG_DIR","DREG_DIR"):("1111nnn0mmm00010","FE"),
("FNEG","","DREG_DIR"):("1111nnn001001101","LS"),
("FSQRT","","DREG_DIR"):("1111nnn001101101","FE"),
("FSUB","DREG_DIR","DREG_DIR"):("1111nnn0mmm00001","FE"),
("FTRC","DREG_DIR","REG_FPUL"):("1111mmm000111101","FE"),
("LDS","REG_DIR","REG_FPSCR"):("0100mmmm01101010","CO"),
("LDS","REG_DIR","REG_FPUL"):("0100mmmm01011010","LS"),
("LDS.L","REG_IND_POST","REG_FPSCR"):("0100mmmm01100110","CO"),
("LDS.L","REG_IND_POST","REG_FPUL"):("0100mmmm01010110","CO"),
("STS","REG_FPSCR","REG_DIR"):("0000nnnn01101010","CO"),
("STS","REG_FPUL","REG_DIR"):("0000nnnn01011010","LS"),
("STS.L","REG_FPSCR","REG_IND_PRE"):("0100nnnn01100010","CO"),
("STS.L","REG_FPUL","REG_IND_PRE"):("0100nnnn01010010","CO"),
("FMOV","DREG_DIR","XREG_DIR"):("1111nnn1mmm01100","LS"),
("FMOV","XREG_DIR","DREG_DIR"):("1111nnn0mmm11100","LS"),
("FMOV","XREG_DIR","XREG_DIR"):("1111nnn1mmm11100","LS"),
("FMOV","REG_IND","XREG_DIR"):("1111nnn1mmmm1000","LS"),
("FMOV","REG_IND_POST","XREG_DIR"):("1111nnn1mmmm1001","LS"),
("FMOV","IND_REG_IND","DREG_DIR"):("1111nnn1mmmm0110","LS"),
("FMOV","XREG_DIR","REG_IND"):("1111nnnnmmm11010","LS"),
("FMOV","XREG_DIR","REG_IND_PRE"):("1111nnnnmmm11011","LS"),
("FMOV","XREG_DIR","IND_REG_IND"):("1111nnnnmmm10111","LS"),
("FIPR","FVREG_DIR","FVREG_DIR"):("1111nnmm11101101","FE"),
("FTRV","REG_XMTRX","FVREG_DIR"):("1111nn0111111101","FE"),
("FRCHG","",""):("1111101111111101","FE"),
("FSCHG","",""):("1111001111111101","FE"),
("FMOV.S","REG_IND","FREG_DIR"):("1111nnnnmmmm1000","LS"),
("FMOV.S","IND_REG_IND","FREG_DIR"):("1111nnnnmmmm0110","LS"),
("FMOV.S","REG_IND_POST","FREG_DIR"):("1111nnnnmmmm1001","LS"),
("FMOV.S","FREG_DIR","REG_IND"):("1111nnnnmmmm1010","LS"),
("FMOV.S","FREG_DIR","REG_IND_PRE"):("1111nnnnmmmm1011","LS"),
("FMOV.S","FREG_DIR","IND_REG_IND"):("1111nnnnmmmm0111","LS"),
("SLEEP","",""):("0000000000011011","CO"),
("RTE","",""):("0000000000101011","CO"),
("LDTLB","",""):("0000000000111000","CO"),
("LDC.L","REG_IND_POST","REG_SR"):("0100mmmm00000111","CO"),
("LDC","REG_DIR","REG_SR"):("0100mmmm00001110","CO"),
("LDC.L","REG_IND_POST","REG_VBR"):("0100mmmm00100111","LS"),
("LDC","REG_DIR","REG_VBR"):("0100mmmm00101110","LS"),
("LDC","REG_DIR","REG_DBR"):("0100mmmm11111010","CO"),
("LDC.L","REG_IND_POST","REG_SSR"):("0100mmmm00110111","LS"),
("LDC.L","REG_IND_POST","REG_DBR"):("0100mmmm11110110","CO"),
("LDC","REG_DIR","REG_SSR"):("0100mmmm00111110","LS"),
("LDC","REG_DIR","REG_SPC"):("0100mmmm01001110","LS"),
("LDC.L","REG_IND_POST","REG_BANK"):("0100mmmm1nnn0111","LS"),
("LDC","REG_DIR","REG_BANK"):("0100mmmm1nnn1110","LS"),
("LDC.L","REG_IND_POST","REG_SGR"):("0100mmmm00110110","CO"),
("LDC","REG_DIR","REG_SGR"):("0100mmmm00111010","CO"),
("LDC.L","REG_IND_POST","REG_SPC"):("0100mmmm01000111","LS"),
("FSRRA","","FREG_DIR"):("1111nnnn01111101","FE"),
("FSCA","REG_FPUL","DREG_DIR"):("1111nnn011111101","FE"),
("MOVCO.L","REG_R0","REG_IND"):("0000nnnn01110011","CO"),
("MOVLI.L","REG_IND","REG_R0"):("0000mmmm01100011","CO"),
("MOVUA.L","REG_IND","REG_R0"):("0100mmmm10101001","LS"),
("MOVUA.L","REG_IND_POST","REG_R0"):("0100mmmm11101001","LS"),
("SYNCO","",""):("0000000010101011","CO"),
("PREFI","","REG_IND"):("0000nnnn11010011","CO"),
("ICBI","","REG_IND"):("0000nnnn11100011","CO"),
("FPCHG","",""):("1111011111111101","FE"),

}

